language: node_js

node_js:
  - "0.12"
  - "0.10"
  - iojs

matrix:
  fast_finish: true
  allow_failures:
    - node_js: iojs

branches:
  only:
    - master

before_script:
  - git fetch --tags
  - npm install bower -g
  - npm install gulp -g

script:
- npm install
- bower install
  - gulp test
  - gulp protractor

cache:
  directories:
    - node_modules
    - bower_components

notifications:
  email:
    - joho1710@gmail.com
